### ISSUE TITLE
Inquiry about OpenCL 1.2 Compatibility

### ISSUE THREAD

**Issue by masahiro120** [artyom-beilis/pytorch_dlprim#92]
Dear Contributors,

Thank you for your great work on this project! I appreciate the effort in integrating OpenCL as a backend for PyTorch.
I noticed that this repository is designed with OpenCL 2 in mind. However, I am currently working in an environment where only OpenCL 1.2 is available. I would like to ask:

1. Is it possible to use this repository with OpenCL 1.2?
2. If not directly compatible, could you point me to a specific commit or provide guidance on how I could adapt the code for OpenCL 1.2?

I am interested in utilizing this library for my research and would be very grateful for any assistance or suggestions.
Thank you for your time and support!

**Comment by artyom-beilis** [comment]
Yes it supports OpenCL 1.2 (even 1.1)

Most nVidia drivers work only for OpenCL 1.2.

What GPU are you trying to use it with?

**Comment by masahiro120** [comment]
Dear Contributors,

Thank you for your continued support and the detailed feedback provided earlier. I would like to provide further context regarding my issue.

I am not working in a GPU-based environment but instead targeting multi-/many-core devices that support OpenCL 1.2. In this environment, I executed the following commands:

---

### Execution Commands:
```bash
python3.10 -m venv dlprim
source dlprim/bin/activate
git clone --recurse-submodules https://github.com/artyom-beilis/pytorch_dlprim.git
cd pytorch_dlprim/
pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cpu
pip install torchvision==0.19.0 numpy
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=$VIRTUAL_ENV/lib/python3.10/site-packages/torch/share/cmake/Torch -DCMAKE_INSTALL_PREFIX=$PWD/install/location -DCMAKE_INCLUDE_PATH=/path/to/include/ -DCMAKE_LIBRARY_PATH=/path/to/lib ..
make -j4
sudo make install
cd ..
export PYTHONPATH=$PWD/build/install/location/python:$PYTHONPATH
python mnist.py --device ocl:0
```

---

### Error Details:
While running the above commands, I encountered the following error:
```plaintext
Traceback (most recent call last):
  File "/home/hassu-/pytorch_dlprim/mnist.py", line 180, in <module>
    main()
  File "/home/hassu-/pytorch_dlprim/mnist.py", line 171, in main
    train(args, model, device, train_loader, optimizer, epoch,args.profile)
  File "/home/hassu-/pytorch_dlprim/mnist.py", line 64, in train
    loss = single_run(data,target)
  File "/home/hassu-/pytorch_dlprim/mnist.py", line 54, in single_run
    output = model(data)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hassu-/pytorch_dlprim/mnist.py", line 29, in forward
    x = self.conv1(x)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hassu-/dlprim/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Failed to build program source sgemm with parameters -cl-std=CL2.0 -DTILE_SIZE_M=32 -DTILE_SIZE_N=32 -DBLOCK_SIZE_M=4 -DBLOCK_SIZE_N=4 -DTILE_SIZE_K=32 -DTILE_OFFSET=0 -DBIAS=0 -DATRANS=0 -DBTRANS=1 -DIM2COL_OCHAN=676 -DCONVGEMM=1 -DKERN_H=3 -DKERN_W=3 -DDILATE_H=1 -DDILATE_W=1 -DPAD_H=0 -DPAD_W=0 -DSTRIDE_H=1 -DSTRIDE_W=1 -DGROUPS=1 -DCHANNELS_IN=1 -DSRC_COLS=28 -DSRC_ROWS=28 -DIMG_COLS=26 -DIMG_ROWS=26 -DREDUCE_K=1 -DACTIVATION=0 log:
For device: MPPA Coolidge
Build option -cl-std specified OpenCL C version 2.0,but device (null) doesn't support that OpenCL C version.

clBuildErrorCode: -11
```

---

### Context and Questions:
- My target environment only supports OpenCL 1.2, and the error indicates that `-cl-std=CL2.0` is being specified during the program build process, which is incompatible with my device.
- Given your earlier response indicating support for OpenCL 1.2 (or even 1.1), I would like to confirm:
  - Is there a specific configuration or flag to ensure compatibility with OpenCL 1.2?
  - Could there be a way to modify the build process to explicitly target OpenCL 1.2, avoiding the `-cl-std=CL2.0` setting?

---

Thank you for your time and guidance. Your assistance will be invaluable as I work towards utilizing this library in my research.

**Comment by artyom-beilis** [comment]
Currently pytorch dlprim does not target or optimized CPU OpenCL implementation
